# Generated by Django 3.2 on 2023-04-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionsResonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dailyemotion',
            name='emotions_resonate',
            field=models.ManyToManyField(to='main.EmotionsResonate'),
        ),
    ]
