# Generated by Django 3.2 on 2023-04-14 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mytododone_my_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytododone',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
