# Generated by Django 3.2.4 on 2023-04-20 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230420_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='diary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.diary'),
        ),
    ]
