# Generated by Django 3.2.4 on 2023-04-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='assets/img/smile1.png', upload_to='media'),
        ),
    ]
