# Generated by Django 3.2.4 on 2023-04-27 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20230427_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='diary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='main.diary'),
        ),
    ]
